name: mapsindoors_googlemaps
description: A MapsIndoors flutter plugin using the Mapbox platform for Android and iOS app usage.
version: 2.1.6
repository: https://github.com/MapsPeople/mapsindoors_flutter_googlemaps
homepage: https://www.mapsindoors.com/

environment:
  sdk: ">=2.18.0 <4.0.0"
  flutter: ">=2.5.0"

flutter:
  plugin:
    platforms:
      android:
        default_package: mapsindoors_googlemaps_android
      ios:
        default_package: mapsindoors_googlemaps_ios

dependencies:
  flutter:
    sdk: flutter
  mapsindoors_googlemaps_android: ^2.1.6
  mapsindoors_googlemaps_ios: ^2.1.6
  mapsindoors_platform_interface: ^2.1.6

dev_dependencies:
  flutter_lints: ^3.0.1
  flutter_test:
    sdk: flutter
  plugin_platform_interface: ^2.0.0
  